CREATE TABLE files
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name VARCHAR(255),
    file_type VARCHAR(255),
    file_size BIGINT,
    file_data BLOB,
    CONSTRAINT pk_files PRIMARY KEY (id)
);